#!/usr/bin/env node

/**
 * Environment Setup Script for NicãoFlix
 * 
 * This script helps set up environment variables for local development
 * and provides guidance for Vercel deployment.
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

const ENV_FILE = path.join(process.cwd(), '.env.local');
const ENV_EXAMPLE = path.join(process.cwd(), '.env.example');

console.log('🚀 NicãoFlix Environment Setup\n');

// Check if .env.local already exists
if (fs.existsSync(ENV_FILE)) {
  console.log('⚠️  .env.local already exists!');
  rl.question('Do you want to overwrite it? (y/N): ', (answer) => {
    if (answer.toLowerCase() === 'y') {
      setupEnvironment();
    } else {
      console.log('Setup cancelled. Your existing .env.local was not modified.');
      rl.close();
    }
  });
} else {
  setupEnvironment();
}

function setupEnvironment() {
  console.log('\n📝 Setting up environment variables...\n');
  
  const questions = [
    {
      key: 'NEXT_PUBLIC_API_BASE_URL',
      question: 'API Base URL (default: https://superflixapi.run): ',
      default: 'https://superflixapi.run'
    },
    {
      key: 'NEXT_PUBLIC_SITE_URL',
      question: 'Site URL (default: http://localhost:3000): ',
      default: 'http://localhost:3000'
    },
    {
      key: 'NEXT_PUBLIC_SITE_NAME',
      question: 'Site Name (default: NicãoFlix): ',
      default: 'NicãoFlix'
    },
    {
      key: 'NEXT_PUBLIC_ENABLE_SERVICE_WORKER',
      question: 'Enable Service Worker? (Y/n): ',
      default: 'true',
      transform: (val) => val.toLowerCase() !== 'n' ? 'true' : 'false'
    },
    {
      key: 'NEXT_PUBLIC_ENABLE_SYNC',
      question: 'Enable Content Sync? (Y/n): ',
      default: 'true',
      transform: (val) => val.toLowerCase() !== 'n' ? 'true' : 'false'
    },
    {
      key: 'NEXT_PUBLIC_SYNC_INTERVAL',
      question: 'Sync Interval in ms (default: 3600000 = 1 hour): ',
      default: '3600000'
    }
  ];

  const envVars = {};
  let currentIndex = 0;

  function askQuestion() {
    if (currentIndex >= questions.length) {
      writeEnvFile(envVars);
      return;
    }

    const q = questions[currentIndex];
    rl.question(q.question, (answer) => {
      const value = answer.trim() || q.default;
      envVars[q.key] = q.transform ? q.transform(value) : value;
      currentIndex++;
      askQuestion();
    });
  }

  askQuestion();
}

function writeEnvFile(envVars) {
  const envContent = `# NicãoFlix Environment Variables
# Generated by setup script on ${new Date().toISOString()}

# API Configuration
NEXT_PUBLIC_API_BASE_URL=${envVars.NEXT_PUBLIC_API_BASE_URL}

# Site Configuration
NEXT_PUBLIC_SITE_URL=${envVars.NEXT_PUBLIC_SITE_URL}
NEXT_PUBLIC_SITE_NAME=${envVars.NEXT_PUBLIC_SITE_NAME}

# Feature Flags
NEXT_PUBLIC_ENABLE_SERVICE_WORKER=${envVars.NEXT_PUBLIC_ENABLE_SERVICE_WORKER}
NEXT_PUBLIC_ENABLE_SYNC=${envVars.NEXT_PUBLIC_ENABLE_SYNC}
NEXT_PUBLIC_SYNC_INTERVAL=${envVars.NEXT_PUBLIC_SYNC_INTERVAL}

# Performance
NEXT_PUBLIC_IMAGE_QUALITY=85
NEXT_PUBLIC_PREFETCH_ENABLED=true

# Development
NODE_ENV=development
`;

  try {
    fs.writeFileSync(ENV_FILE, envContent);
    console.log('\n✅ Environment file created successfully!');
    console.log(`📄 File location: ${ENV_FILE}\n`);
    
    console.log('📋 Next steps:');
    console.log('1. Review the .env.local file');
    console.log('2. Run: npm run dev');
    console.log('3. Open: http://localhost:3000\n');
    
    console.log('🚀 For Vercel deployment:');
    console.log('1. Go to your Vercel project settings');
    console.log('2. Navigate to Environment Variables');
    console.log('3. Add the same variables (use production values)');
    console.log('4. See DEPLOYMENT.md for detailed instructions\n');
    
  } catch (error) {
    console.error('❌ Error writing environment file:', error.message);
  }
  
  rl.close();
}

rl.on('close', () => {
  process.exit(0);
});
